/* JavaScript file Generated by
 * Creativyst(tm) CSV converter
 *   (www.creativyst.com)
 * 
 * (C) Copyright 2002-2003, Creativyst, Inc.
 * 
 * Permission is hereby granted to use,
 * distribute, and change this file for any
 * reason, provided this entire comment remains
 * intact with the work.
 * 
 *
*/

/*JSCPragma:StartCompress
*/

var lsz = 47;

var Offensespheres = Array([lsz]);
var Usedby = Array([lsz]);

Offensespheres[0] = "Awaken ATK";
Usedby[0] = "Sidara, Zaan";

Offensespheres[1] = "Awaken DEF";
Usedby[1] = "Gafgard";

Offensespheres[2] = "Awaken SPD";
Usedby[2] = "Dragoon, Dart, Lancelot, Beach boy Luke";

Offensespheres[3] = "Barrage";
Usedby[3] = "Nami, Petra";

Offensespheres[4] = "Blunder Blast";
Usedby[4] = "Vicious";

Offensespheres[5] = "Bolt";
Usedby[5] = "Mage";

Offensespheres[6] = "Brave Lighting";
Usedby[6] = "Zeig";

Offensespheres[7] = "Break ATK";
Usedby[7] = "Pirate";

Offensespheres[8] = "Break DEF";
Usedby[8] = "Berserker, Monk, Zanmato, Lavitz";

Offensespheres[9] = "Break SPD";
Usedby[9] = "Ninja ,Finn, Morgan";

Offensespheres[10] = "Death Blossom";
Usedby[10] = "Yojimbo";

Offensespheres[11] = "Double Punch";
Usedby[11] = "Donno, Fiora";

Offensespheres[12] = "Double Shot";
Usedby[12] = "Archer";

Offensespheres[13] = "Double Slash";
Usedby[13] = "Warrior, Arc";

Offensespheres[14] = "Dualcast";
Usedby[14] = "Druid";

Offensespheres[15] = "Fire";
Usedby[15] = "Ominas, Nobunaga";

Offensespheres[16] = "Focus";
Usedby[16] = "Rogue, Asher, Sasuke";

Offensespheres[17] = "Grand Bolt";
Usedby[17] = "Azazel";

Offensespheres[18] = "Grand Fire";
Usedby[18] = "Atnas";

Offensespheres[19] = "Grand Opus";
Usedby[19] = "Mercutio, Trill, Mephistopheles";

Offensespheres[20] = "Grand Potion";
Usedby[20] = "Dr. Gloom";

Offensespheres[21] = "Grand Shard";
Usedby[21] = "Belle, Wallace";

Offensespheres[22] = "Heavenly Arrow";
Usedby[22] = "Artemis";

Offensespheres[23] = "Intimidate";
Usedby[23] = "Cytomandra";

Offensespheres[24] = "Lightning Cut";
Usedby[24] = "Rex";

Offensespheres[25] = "Mighty Opus";
Usedby[25] = "Blaine";

Offensespheres[26] = "Mightybolt";
Usedby[26] = "Sorcerer, Lilith";

Offensespheres[27] = "Mightyfire";
Usedby[27] = "Warlock";

Offensespheres[28] = "Obliterate ATK";
Usedby[28] = "Ozymandias";

Offensespheres[29] = "Obliterate DEF";
Usedby[29] = "Ringabolt, Ruthie";

Offensespheres[30] = "Obliterate SPD";
Usedby[30] = "Arden, Leos";

Offensespheres[31] = "Oblivion";
Usedby[31] = "Chrollo, Luke";

Offensespheres[32] = "Opus";
Usedby[32] = "Randall";

Offensespheres[33] = "Potion";
Usedby[33] = "Alchemist, Arthur";

Offensespheres[34] = "Quad Cast";
Usedby[34] = "Runeia";

Offensespheres[35] = "Quadra Punch";
Usedby[35] = "Remmy, Macho Ringabolt";

Offensespheres[36] = "Quadra Shot";
Usedby[36] = "Rorick";

Offensespheres[37] = "Quadra Slash";
Usedby[37] = "Dragonslayer, Agamnenon, Malphas, Roland";

Offensespheres[38] = "Shard";
Usedby[38] = "Necromancer, Caius";

Offensespheres[39] = "Superstar Flash";
Usedby[39] = "Arpeggio";

Offensespheres[40] = "Tricast";
Usedby[40] = "Azelas, Hadrian";

Offensespheres[41] = "Triple Punch";
Usedby[41] = "Ragnas";

Offensespheres[42] = "Triple Shot";
Usedby[42] = "Hunter, Grom, Bikini Promecia, Genji";

Offensespheres[43] = "Vamp Slash";
Usedby[43] = "Grimwald";

Offensespheres[44] = "Vampcast";
Usedby[44] = "Dismara, Raven";

Offensespheres[45] = "Wide Slash";
Usedby[45] = "Orion";


/* JavaScript file Generated by
 * Creativyst(tm) CSV converter
 *   (www.creativyst.com)
 * 
 * (C) Copyright 2002-2003, Creativyst, Inc.
 * 
 * Permission is hereby granted to use,
 * distribute, and change this file for any
 * reason, provided this entire comment remains
 * intact with the work.
 * 
 *
*/

/*JSCPragma:StartCompress
*/

var lsz = 28;

var Defensespheres = Array([lsz]);
var Usedby = Array([lsz]);

Defensespheres[0] = "Aegis";
Usedby[0] = "Paladin, Gafgard, Promecia";

Defensespheres[1] = "Bolster ATK";
Usedby[1] = "Sidara, Zaan, Bikini Promecia";

Defensespheres[2] = "Bolster DEF";
Usedby[2] = "Butz, Malphas, Varus, Wallace";

Defensespheres[3] = "Bolster SPD";
Usedby[3] = "Dragoon, Rogue, Asher, Dart, Randall";

Defensespheres[4] = "Brave Song";
Usedby[4] = "Bard, Juliet, Trill";

Defensespheres[5] = "Counter Cast";
Usedby[5] = "Azazel, Caius, Runeia";

Defensespheres[6] = "Counter Punch";
Usedby[6] = "Monk, Macho Ringabolt";

Defensespheres[7] = "Counter Slash";
Usedby[7] = "Knight";

Defensespheres[8] = "Death Touch";
Usedby[8] = "Yojimbo";

Defensespheres[9] = "Defense Song";
Usedby[9] = "Erika";

Defensespheres[10] = "Deflect Projectiles";
Usedby[10] = "Dragonslayer, Remmy";

Defensespheres[11] = "Evade";
Usedby[11] = "Ninja, Donno, Finn, Grimwald, Lancelot, Leos";

Defensespheres[12] = "Healing Song";
Usedby[12] = "Cleric, Alice";

Defensespheres[13] = "Magna";
Usedby[13] = "Azelas, Chrollo, Hadrian, Ominas, Nobunaga";

Defensespheres[14] = "Mimic";
Usedby[14] = "Alchemist, Rorick, Wedge, Mephistopheles";

Defensespheres[15] = "Ninjutsu";
Usedby[15] = "Anna, Sasuke";

Defensespheres[16] = "Nullbolt";
Usedby[16] = "Mage";

Defensespheres[17] = "Nullfire";
Usedby[17] = "Thief";

Defensespheres[18] = "Nullshard";
Usedby[18] = "Eoqueth";

Defensespheres[19] = "Quick Punch";
Usedby[19] = "Fiora";

Defensespheres[20] = "Quick Shot";
Usedby[20] = "Hunter, Vicious, Genji";

Defensespheres[21] = "Quick Slash";
Usedby[21] = "Agamemnon, Luna";

Defensespheres[22] = "Quickcast";
Usedby[22] = "Sorcerer, Dismara,Lilith, Towel mage Juliet";

Defensespheres[23] = "Regal Stance";
Usedby[23] = "Cytomandra, Osymandias, Ringabolt";

Defensespheres[24] = "Speed Song";
Usedby[24] = "Mel";

Defensespheres[25] = "Thornbrew";
Usedby[25] = "Dr. Gloom";

Defensespheres[26] = "Tornado Guard";
Usedby[26] = "Arthur";


/* JavaScript file Generated by
 * Creativyst(tm) CSV converter
 *   (www.creativyst.com)
 * 
 * (C) Copyright 2002-2003, Creativyst, Inc.
 * 
 * Permission is hereby granted to use,
 * distribute, and change this file for any
 * reason, provided this entire comment remains
 * intact with the work.
 * 
 *
*/

/*JSCPragma:StartCompress
*/

var lsz = 20;

var Supportspheres = Array([lsz]);
var Usedby = Array([lsz]);

Supportspheres[0] = "Blue Song";
Usedby[0] = "Erika";

Supportspheres[1] = "Boost ATK";
Usedby[1] = "Warlock, Warrior, Butz, Ruthie, Arc";

Supportspheres[2] = "Boost DEF";
Usedby[2] = "Knight, Paladin, Zanmato";

Supportspheres[3] = "Boost SPD";
Usedby[3] = "Archer, Necromancer, Morgan, Ragnas, Wedge, Lavitz";

Supportspheres[4] = "Cure";
Usedby[4] = "Cleric, Artemis";

Supportspheres[5] = "Dance";
Usedby[5] = "Bard";

Supportspheres[6] = "Grand Cure";
Usedby[6] = "Eoqueth";

Supportspheres[7] = "Green Song";
Usedby[7] = "Juliet";

Supportspheres[8] = "Guard";
Usedby[8] = "Dragonslayer, Agamemnon, Arden, Grom, Promecia, Ringabolt, Varus";

Supportspheres[9] = "Hex Hellion";
Usedby[9] = "Atnas";

Supportspheres[10] = "Interrupt Cast";
Usedby[10] = "Towel mage Juliet, Raven";

Supportspheres[11] = "Interrupt Shot";
Usedby[11] = "Thief, Anna";

Supportspheres[12] = "Interrupt Slash";
Usedby[12] = "Berserker, Roland, Beach boy Luke";

Supportspheres[13] = "Mighty Cure";
Usedby[13] = "Alice, Luna";

Supportspheres[14] = "Reaper Shot";
Usedby[14] = "Leos, Lloyd";

Supportspheres[15] = "Red Song";
Usedby[15] = "Mercutio";

Supportspheres[16] = "Restore";
Usedby[16] = "Druid, Azelas ,Belle, Nami";

Supportspheres[17] = "Sing";
Usedby[17] = "Pirate, Mel";

Supportspheres[18] = "Symphony No.99";
Usedby[18] = "Trill";


