var array2 = ["idd0", "idd1", "idd2", "idd3", "idd4", "idd5", "idd6"];

/* JavaScript file Generated by
 * Creativyst(tm) CSV converter
 *   (www.creativyst.com)
 * 
 * (C) Copyright 2002-2003, Creativyst, Inc.
 * 
 * Permission is hereby granted to use,
 * distribute, and change this file for any
 * reason, provided this entire comment remains
 * intact with the work.
 * 
 *
*/

/*JSCPragma:StartCompress
*/

var lsz = 22;

var Name = Array([lsz]);
var Spritename = Array([lsz]);
var Used = Array([lsz]);
var Offense = Array([lsz]);
var Defense = Array([lsz]);
var Support = Array([lsz]);

Name[0] = "Alchemist";
Spritename[0] = "Alchemist";
Used[0] = "Dr. Gloom, Randall, Wedge, Alice, Arthur, Remmy";
Offense[0] = "Potion III";
Defense[0] = "Mimic III";
Support[0] = "None";

Name[1] = "Archer";
Spritename[1] = "Archer";
Used[1] = "Eoqueth, Rorick, Artemis, Grom, Lloyd, Petra";
Offense[1] = "Double Shot III";
Defense[1] = "None";
Support[1] = "Boost SPD III";

Name[2] = "Bard";
Spritename[2] = "Bard";
Used[2] = "Finn, Juliet, Arpeggio, Mercutio, Donno, Blaine";
Offense[2] = "None";
Defense[2] = "Brave Song III";
Support[2] = "Dance III";

Name[3] = "Berserker";
Spritename[3] = "Berserker";
Used[3] = "Butz, Ragnas, Runeia, Sidara";
Offense[3] = "Break DEF II";
Defense[3] = "None";
Support[3] = "Interrupt Slash I";

Name[4] = "Cleric";
Spritename[4] = "Cleric";
Used[4] = "Raven, Wallace, Luna, Artemis, Belle, Promecia";
Offense[4] = "None";
Defense[4] = "Healing Song III";
Support[4] = "Cure III";

Name[5] = "Dragon Slayer";
Spritename[5] = "Dragonslayer";
Used[5] = "Grimwald, Yojimbo, Orion, Ringabolt, Ozymandias, Zeig";
Offense[5] = "Quadra Slash I";
Defense[5] = "Deflect Projectiles II";
Support[5] = "Guard I";

Name[6] = "Dragoon";
Spritename[6] = "Dragoon";
Used[6] = "Ozymandias, Lavitz, Lancelot, Zanmato, Gafgard";
Offense[6] = "Awaken SPD III";
Defense[6] = "Bolster SPD III";
Support[6] = "None";

Name[7] = "Druid";
Spritename[7] = "Druid";
Used[7] = "Raven, Randall, Nami, Butz, Hadrian";
Offense[7] = "Dualcast III";
Defense[7] = "None";
Support[7] = "Restore II";

Name[8] = "Hunter";
Spritename[8] = "Hunter";
Used[8] = "Morgan, Nami, Sidara, Mel, Erika, Alice";
Offense[8] = "Triple Shot II";
Defense[8] = "Quick shot I";
Support[8] = "None";

Name[9] = "Knight";
Spritename[9] = "Knight";
Used[9] = "Grimwald, Arden, Promecia, Varus, Roland";
Offense[9] = "None";
Defense[9] = "Counter Slash II";
Support[9] = "Boost DEF III";

Name[10] = "Mage";
Spritename[10] = "Mage";
Used[10] = "Atnas, Mercutio, Lilith, Belle";
Offense[10] = "Bolt III";
Defense[10] = "Nullbolt III";
Support[10] = "None";

Name[11] = "Monk";
Spritename[11] = "Monk";
Used[11] = "Lancelot, Donno, Ragnas, Mel, Remmy";
Offense[11] = "Break DEF II";
Defense[11] = "Counter Punch II";
Support[11] = "None";

Name[12] = "Necromancer";
Spritename[12] = "Necromancer";
Used[12] = "Zeig, Dr. Gloom, Azazel, Ominas";
Offense[12] = "Shard III";
Defense[12] = "None";
Support[12] = "Boost SPD III";

Name[13] = "Ninja";
Spritename[13] = "Ninja";
Used[13] = "Yojimbo, Zanmato, Blaine, Erika, Sasuke";
Offense[13] = "Break SPD II";
Defense[13] = "Evade I";
Support[13] = "None";

Name[14] = "Paladin";
Spritename[14] = "Paladin";
Used[14] = "Ringabolt, Hadrian, Gafgard, Arden, Wallace, Wedge";
Offense[14] = "None";
Defense[14] = "Aegis II";
Support[14] = "Boost DEF III";

Name[15] = "Pirate";
Spritename[15] = "Pirate";
Used[15] = "Ominas, Ruthie, Morgan, Vicious, Finn";
Offense[15] = "Break ATK II";
Defense[15] = "None";
Support[15] = "Sing III";

Name[16] = "Rogue";
Spritename[16] = "Rogue";
Used[16] = "Ruthie, Anna, Roland, Grom, Dart";
Offense[16] = "Focus III";
Defense[16] = "Bolster SPD III";
Support[16] = "None";

Name[17] = "Sorcerer";
Spritename[17] = "Sorcerer";
Used[17] = "Azazel, Luke, Juliet";
Offense[17] = "Mightybolt II";
Defense[17] = "Quickcast I";
Support[17] = "None";

Name[18] = "Thief";
Spritename[18] = "Thief";
Used[18] = "Arpeggio, Arthur, Fiora, Varus, Dart, Petra";
Offense[18] = "None";
Defense[18] = "Nullfire II";
Support[18] = "Interrupt Shot I";

Name[19] = "Warlock";
Spritename[19] = "Warlock";
Used[19] = "Orion, Runeia, Rorick, Lilith, Sasuke";
Offense[19] = "Mightyfire II";
Defense[19] = "None";
Support[19] = "Boost ATK III";

Name[20] = "Warrior";
Spritename[20] = "Warrior";
Used[20] = "Zaan, Lavitz, Caius, Luna, Arc, Rex,";
Offense[20] = "Double Slash III";
Defense[20] = "None";
Support[20] = "Boost ATK III";


