var array = ["id0", "id1", "id2", "id3", "id4"];

/* JavaScript file Generated by
 * Creativyst(tm) CSV converter
 *   (www.creativyst.com)
 * 
 * (C) Copyright 2002-2003, Creativyst, Inc.
 * 
 * Permission is hereby granted to use,
 * distribute, and change this file for any
 * reason, provided this entire comment remains
 * intact with the work.
 * 
 *
*/

/*JSCPragma:StartCompress
*/

var lsz = 81;

var Character = Array([lsz]);
var Spritename = Array([lsz]);
var Offensivesphere = Array([lsz]);
var Defensivesphere = Array([lsz]);
var Supportsphere = Array([lsz]);
var MixSource = Array([lsz]);
var Class = Array([lsz]);
var HP = Array([lsz]);
var ATK = Array([lsz]);
var DEF = Array([lsz]);
var SPD = Array([lsz]);

Character[0] = "Agamemnon";
Spritename[0] = "Agamemnon";
Offensivesphere[0] = "Quadra Slash I";
Defensivesphere[0] = "Quick Slash I";
Supportsphere[0] = "Guard I";
MixSource[0] = "Goody bag";
Class[0] = "Axe";
HP[0] = "100";
ATK[0] = "120";
DEF[0] = "52";
SPD[0] = "54";

Character[1] = "Alice";
Spritename[1] = "Alice";
Offensivesphere[1] = "None";
Defensivesphere[1] = "Healing Song III";
Supportsphere[1] = "Mightycure II";
MixSource[1] = "Alchemist + Hunter";
Class[1] = "Potion";
HP[1] = "104";
ATK[1] = "86";
DEF[1] = "55";
SPD[1] = "54";

Character[2] = "Anna";
Spritename[2] = "Anna";
Offensivesphere[2] = "None";
Defensivesphere[2] = "Ninjustu I";
Supportsphere[2] = "Interrupt Shot I";
MixSource[2] = "Rogue + Ninja";
Class[2] = "Dagger";
HP[2] = "107";
ATK[2] = "89";
DEF[2] = "40";
SPD[2] = "60";

Character[3] = "Arc";
Spritename[3] = "Arc";
Offensivesphere[3] = "None";
Defensivesphere[3] = "None";
Supportsphere[3] = "None";
MixSource[3] = "Warrior + Rogue";
Class[3] = "Sword";
HP[3] = "106";
ATK[3] = "86";
DEF[3] = "52";
SPD[3] = "53";

Character[4] = "Arden";
Spritename[4] = "Arden";
Offensivesphere[4] = "Obliterate SPD I";
Defensivesphere[4] = "None";
Supportsphere[4] = "Guard I";
MixSource[4] = "Knight + Paladin";
Class[4] = "Lance";
HP[4] = "135";
ATK[4] = "80";
DEF[4] = "60";
SPD[4] = "48";

Character[5] = "Arpeggio";
Spritename[5] = "Arpeggio";
Offensivesphere[5] = "Superstar Flash I";
Defensivesphere[5] = "None";
Supportsphere[5] = "None";
MixSource[5] = "Thief + Bard";
Class[5] = "Harp";
HP[5] = "102";
ATK[5] = "82";
DEF[5] = "52";
SPD[5] = "63";

Character[6] = "Artemis";
Spritename[6] = "Artemis";
Offensivesphere[6] = "Heavenly Arrow II";
Defensivesphere[6] = "None";
Supportsphere[6] = "Cure III";
MixSource[6] = "Archer + Cleric";
Class[6] = "Bow";
HP[6] = "107";
ATK[6] = "87";
DEF[6] = "50";
SPD[6] = "52";

Character[7] = "Arthur";
Spritename[7] = "Arthur";
Offensivesphere[7] = "Potion III";
Defensivesphere[7] = "Tornado Guard I";
Supportsphere[7] = "None";
MixSource[7] = "Thief + Alchemist";
Class[7] = "Potion";
HP[7] = "105";
ATK[7] = "85";
DEF[7] = "55";
SPD[7] = "55";

Character[8] = "Asher";
Spritename[8] = "Asher";
Offensivesphere[8] = "Focus III";
Defensivesphere[8] = "Bolster SPD III";
Supportsphere[8] = "None";
MixSource[8] = "Dark rune";
Class[8] = "Dagger";
HP[8] = "100";
ATK[8] = "101";
DEF[8] = "48";
SPD[8] = "53";

Character[9] = "Atnas";
Spritename[9] = "Atnas";
Offensivesphere[9] = "Grandfire I";
Defensivesphere[9] = "None";
Supportsphere[9] = "Hex Hellion I";
MixSource[9] = "Mage + Necromancer";
Class[9] = "Staff";
HP[9] = "95";
ATK[9] = "98";
DEF[9] = "47";
SPD[9] = "54";

Character[10] = "Azazel";
Spritename[10] = "Azazel";
Offensivesphere[10] = "Grandbolt I";
Defensivesphere[10] = "Countercast II";
Supportsphere[10] = "None";
MixSource[10] = "Sorcerer + Necromancer";
Class[10] = "Tome";
HP[10] = "100";
ATK[10] = "99";
DEF[10] = "48";
SPD[10] = "53";

Character[11] = "Azelas";
Spritename[11] = "Azelas";
Offensivesphere[11] = "Tricast II";
Defensivesphere[11] = "Magna III";
Supportsphere[11] = "Restore II";
MixSource[11] = "Goody bag";
Class[11] = "Staff";
HP[11] = "99";
ATK[11] = "87";
DEF[11] = "61";
SPD[11] = "65";

Character[12] = "Beach boy Luke";
Spritename[12] = "Beach_boy_Luke";
Offensivesphere[12] = "Awaken SPD III";
Defensivesphere[12] = "None";
Supportsphere[12] = "Interrupt Slash I";
MixSource[12] = "Summer band";
Class[12] = "Lance";
HP[12] = "97";
ATK[12] = "97";
DEF[12] = "68";
SPD[12] = "58";

Character[13] = "Belle";
Spritename[13] = "Belle";
Offensivesphere[13] = "Grandshard II";
Defensivesphere[13] = "None";
Supportsphere[13] = "Restore II";
MixSource[13] = "Mage + Cleric";
Class[13] = "Lance";
HP[13] = "95";
ATK[13] = "87";
DEF[13] = "45";
SPD[13] = "57";

Character[14] = "Bikini Promecia";
Spritename[14] = "BIkini_Promecia";
Offensivesphere[14] = "Triple Shot II";
Defensivesphere[14] = "Bolster ATK III";
Supportsphere[14] = "None";
MixSource[14] = "Summer band";
Class[14] = "Gun";
HP[14] = "100";
ATK[14] = "105";
DEF[14] = "55";
SPD[14] = "62";

Character[15] = "Blaine";
Spritename[15] = "Blaine";
Offensivesphere[15] = "Mighty Opus II";
Defensivesphere[15] = "None";
Supportsphere[15] = "None";
MixSource[15] = "Ninja + Bard";
Class[15] = "Harp";
HP[15] = "102";
ATK[15] = "84";
DEF[15] = "51";
SPD[15] = "60";

Character[16] = "Butz";
Spritename[16] = "Butz";
Offensivesphere[16] = "None";
Defensivesphere[16] = "Bolster DEF III";
Supportsphere[16] = "Boost ATK III";
MixSource[16] = "Berserker + Druid";
Class[16] = "Axe";
HP[16] = "115";
ATK[16] = "99";
DEF[16] = "40";
SPD[16] = "55";

Character[17] = "Caius";
Spritename[17] = "Caius";
Offensivesphere[17] = "Shard III";
Defensivesphere[17] = "Countercast II";
Supportsphere[17] = "None";
MixSource[17] = "Warrior + Warlock";
Class[17] = "Crystal";
HP[17] = "104";
ATK[17] = "90";
DEF[17] = "48";
SPD[17] = "56";

Character[18] = "Chrollo";
Spritename[18] = "Chrollo";
Offensivesphere[18] = "Oblivion III";
Defensivesphere[18] = "Magma III";
Supportsphere[18] = "None";
MixSource[18] = "Dark rune";
Class[18] = "Fist";
HP[18] = "110";
ATK[18] = "73";
DEF[18] = "65";
SPD[18] = "53";

Character[19] = "Cytomandra";
Spritename[19] = "Cytomandra";
Offensivesphere[19] = "Intimidate II";
Defensivesphere[19] = "Regal Stance I";
Supportsphere[19] = "None";
MixSource[19] = "Dark rune";
Class[19] = "Lance";
HP[19] = "104";
ATK[19] = "84";
DEF[19] = "55";
SPD[19] = "56";

Character[20] = "Dart";
Spritename[20] = "Dart";
Offensivesphere[20] = "Awaken SPD III";
Defensivesphere[20] = "Bolster SPD III";
Supportsphere[20] = "None";
MixSource[20] = "Thief + Rogue";
Class[20] = "Dagger";
HP[20] = "89";
ATK[20] = "86";
DEF[20] = "48";
SPD[20] = "67";

Character[21] = "Dismara";
Spritename[21] = "Dismara";
Offensivesphere[21] = "Vampcast II";
Defensivesphere[21] = "Quickcast I";
Supportsphere[21] = "None";
MixSource[21] = "Dark rune";
Class[21] = "Staff";
HP[21] = "95";
ATK[21] = "95";
DEF[21] = "49";
SPD[21] = "58";

Character[22] = "Donno";
Spritename[22] = "Donno";
Offensivesphere[22] = "Double Punch III";
Defensivesphere[22] = "Evade I";
Supportsphere[22] = "None";
MixSource[22] = "Monk + Bard";
Class[22] = "Fist";
HP[22] = "100";
ATK[22] = "90";
DEF[22] = "52";
SPD[22] = "55";

Character[23] = "Dr.Gloom";
Spritename[23] = "Dr_Gloom";
Offensivesphere[23] = "Grand Potion I";
Defensivesphere[23] = "Thorn Brew II";
Supportsphere[23] = "None";
MixSource[23] = "Alchemist + Necromancer";
Class[23] = "Potion";
HP[23] = "110";
ATK[23] = "87";
DEF[23] = "55";
SPD[23] = "54";

Character[24] = "Eoqueth";
Spritename[24] = "Eoqueth";
Offensivesphere[24] = "None";
Defensivesphere[24] = "Nullshard III";
Supportsphere[24] = "Grandcure I";
MixSource[24] = "Archer + Druid";
Class[24] = "Crystal";
HP[24] = "104";
ATK[24] = "78";
DEF[24] = "58";
SPD[24] = "55";

Character[25] = "Erika";
Spritename[25] = "Erika";
Offensivesphere[25] = "None";
Defensivesphere[25] = "Defense Song III";
Supportsphere[25] = "Blue Song II";
MixSource[25] = "Ninja + Hunter";
Class[25] = "Dagger";
HP[25] = "90";
ATK[25] = "92";
DEF[25] = "50";
SPD[25] = "70";

Character[26] = "Finn";
Spritename[26] = "Finn";
Offensivesphere[26] = "Break SPD II";
Defensivesphere[26] = "\rEvade I";
Supportsphere[26] = "None";
MixSource[26] = "Bard + Pirate";
Class[26] = "Gun";
HP[26] = "102";
ATK[26] = "87";
DEF[26] = "50";
SPD[26] = "57";

Character[27] = "Fiora";
Spritename[27] = "Fiora";
Offensivesphere[27] = "Double Punch III";
Defensivesphere[27] = "Quick Punch I";
Supportsphere[27] = "None";
MixSource[27] = "Thief + Monk";
Class[27] = "Fist";
HP[27] = "95";
ATK[27] = "89";
DEF[27] = "32";
SPD[27] = "57";

Character[28] = "Gafgard";
Spritename[28] = "Gafgard";
Offensivesphere[28] = "Awaken DEF III";
Defensivesphere[28] = "Aegis II";
Supportsphere[28] = "None";
MixSource[28] = "Paladin + Dragoon";
Class[28] = "Lance";
HP[28] = "110";
ATK[28] = "70";
DEF[28] = "70";
SPD[28] = "50";

Character[29] = "Grimwald";
Spritename[29] = "Grimwald";
Offensivesphere[29] = "Vamp Slash II";
Defensivesphere[29] = "Evade I";
Supportsphere[29] = "None";
MixSource[29] = "Knight + Dragonslayer";
Class[29] = "Axe";
HP[29] = "104";
ATK[29] = "87";
DEF[29] = "59";
SPD[29] = "54";

Character[30] = "Grom";
Spritename[30] = "Grom";
Offensivesphere[30] = "Triple Shot II";
Defensivesphere[30] = "None";
Supportsphere[30] = "Guard I";
MixSource[30] = "Archer + Rogue";
Class[30] = "Bow";
HP[30] = "115";
ATK[30] = "84";
DEF[30] = "52";
SPD[30] = "48";

Character[31] = "Hadrian";
Spritename[31] = "Hadrian";
Offensivesphere[31] = "Tricast II";
Defensivesphere[31] = "Magna III";
Supportsphere[31] = "None";
MixSource[31] = "Paladin + Druid";
Class[31] = "Staff";
HP[31] = "110";
ATK[31] = "73";
DEF[31] = "65";
SPD[31] = "53";

Character[32] = "Juliet";
Spritename[32] = "Juliet";
Offensivesphere[32] = "None";
Defensivesphere[32] = "Brave Song III";
Supportsphere[32] = "Green Song II";
MixSource[32] = "Bard + Sorcerer";
Class[32] = "Harp";
HP[32] = "104";
ATK[32] = "84";
DEF[32] = "55";
SPD[32] = "56";

Character[33] = "Kylocke";
Spritename[33] = "Kylocke";
Offensivesphere[33] = "Brave Lightning I";
Defensivesphere[33] = "Quickcast I";
Supportsphere[33] = "None";
MixSource[33] = "Dark Rune";
Class[33] = "Tome";
HP[33] = "95";
ATK[33] = "102";
DEF[33] = "55";
SPD[33] = "52";

Character[34] = "Lancelot";
Spritename[34] = "Lancelot";
Offensivesphere[34] = "Awaken SPD III";
Defensivesphere[34] = "Evade I";
Supportsphere[34] = "None";
MixSource[34] = "Monk + Dragoon";
Class[34] = "Lance";
HP[34] = "101";
ATK[34] = "85";
DEF[34] = "60";
SPD[34] = "53";

Character[35] = "Lavitz";
Spritename[35] = "Lavitz";
Offensivesphere[35] = "None";
Defensivesphere[35] = "None";
Supportsphere[35] = "None";
MixSource[35] = "Warrior + Dragoon";
Class[35] = "Lance";
HP[35] = "100";
ATK[35] = "87";
DEF[35] = "56";
SPD[35] = "52";

Character[36] = "Leos";
Spritename[36] = "Leos";
Offensivesphere[36] = "Obliterate SPD I";
Defensivesphere[36] = "None";
Supportsphere[36] = "Reaper Shot I";
MixSource[36] = "Goody bag";
Class[36] = "Dagger";
HP[36] = "115";
ATK[36] = "99";
DEF[36] = "40";
SPD[36] = "75";

Character[37] = "Lilith";
Spritename[37] = "Lilith";
Offensivesphere[37] = "Mighybolt II";
Defensivesphere[37] = "Quickcast I";
Supportsphere[37] = "None";
MixSource[37] = "Mage + Warlock";
Class[37] = "Crystal";
HP[37] = "93";
ATK[37] = "99";
DEF[37] = "40";
SPD[37] = "54";

Character[38] = "Lloyd";
Spritename[38] = "Lloyd";
Offensivesphere[38] = "None";
Defensivesphere[38] = "None";
Supportsphere[38] = "Reaper Shot I";
MixSource[38] = "Archer + Mage";
Class[38] = "Bow";
HP[38] = "91";
ATK[38] = "93";
DEF[38] = "52";
SPD[38] = "64";

Character[39] = "Luke";
Spritename[39] = "Luke";
Offensivesphere[39] = "Oblivion";
Defensivesphere[39] = "None";
Supportsphere[39] = "None";
MixSource[39] = "Berserker + Sorcerer";
Class[39] = "Tome";
HP[39] = "100";
ATK[39] = "101";
DEF[39] = "48";
SPD[39] = "53";

Character[40] = "Luna";
Spritename[40] = "Luna";
Offensivesphere[40] = "Quick Slash II";
Defensivesphere[40] = "None";
Supportsphere[40] = "Mightycure III";
MixSource[40] = "Warrior + Cleric";
Class[40] = "Sword";
HP[40] = "103";
ATK[40] = "82";
DEF[40] = "49";
SPD[40] = "59";

Character[41] = "Macho Ringabolt";
Spritename[41] = "Macho_Ringabolt";
Offensivesphere[41] = "Quadra Punch I";
Defensivesphere[41] = "Counter Punch I";
Supportsphere[41] = "None";
MixSource[41] = "Summer band";
Class[41] = "Fist";
HP[41] = "105";
ATK[41] = "135";
DEF[41] = "48";
SPD[41] = "64";

Character[42] = "Malphas";
Spritename[42] = "Malphas";
Offensivesphere[42] = "Quadra Slash I";
Defensivesphere[42] = "Bolster DEF III";
Supportsphere[42] = "None";
MixSource[42] = "Dark rune";
Class[42] = "Axe";
HP[42] = "110";
ATK[42] = "70";
DEF[42] = "70";
SPD[42] = "50";

Character[43] = "Mel";
Spritename[43] = "Mel";
Offensivesphere[43] = "None";
Defensivesphere[43] = "Speed Song III";
Supportsphere[43] = "Sing III";
MixSource[43] = "Monk + Hunter";
Class[43] = "Fist";
HP[43] = "106";
ATK[43] = "82";
DEF[43] = "56";
SPD[43] = "55";

Character[44] = "Mephistopheles";
Spritename[44] = "Mephistopheles";
Offensivesphere[44] = "None";
Defensivesphere[44] = "None";
Supportsphere[44] = "None";
MixSource[44] = "Dark Rune";
Class[44] = "Fist";
HP[44] = "100";
ATK[44] = "100";
DEF[44] = "52";
SPD[44] = "54";

Character[45] = "Mercutio";
Spritename[45] = "Mercutio";
Offensivesphere[45] = "Grand Opus I";
Defensivesphere[45] = "None";
Supportsphere[45] = "Red Song II";
MixSource[45] = "Mage + Bard";
Class[45] = "Harp";
HP[45] = "99";
ATK[45] = "88";
DEF[45] = "58";
SPD[45] = "51";

Character[46] = "Minotaur";
Spritename[46] = "Minotaur";
Offensivesphere[46] = "None";
Defensivesphere[46] = "None";
Supportsphere[46] = "None";
MixSource[46] = "Dark Rune";
Class[46] = "/";
HP[46] = "180";
ATK[46] = "80";
DEF[46] = "60";
SPD[46] = "48";

Character[47] = "Morgan";
Spritename[47] = "Morgan";
Offensivesphere[47] = "Break SPD III";
Defensivesphere[47] = "None";
Supportsphere[47] = "Boost SPD III";
MixSource[47] = "Hunter + Pirate";
Class[47] = "Gun";
HP[47] = "104";
ATK[47] = "90";
DEF[47] = "45";
SPD[47] = "60";

Character[48] = "Nami";
Spritename[48] = "Nami";
Offensivesphere[48] = "Barrage I";
Defensivesphere[48] = "None";
Supportsphere[48] = "Restore II";
MixSource[48] = "Hinter + Druid";
Class[48] = "Bow";
HP[48] = "110";
ATK[48] = "88";
DEF[48] = "49";
SPD[48] = "56";

Character[49] = "Ominas";
Spritename[49] = "Ominas";
Offensivesphere[49] = "Fire III";
Defensivesphere[49] = "None";
Supportsphere[49] = "Magna III";
MixSource[49] = "Pirate + Necromancer";
Class[49] = "Staff";
HP[49] = "78";
ATK[49] = "99";
DEF[49] = "45";
SPD[49] = "63";

Character[50] = "Orion";
Spritename[50] = "Orion";
Offensivesphere[50] = "Wide Slash I";
Defensivesphere[50] = "None";
Supportsphere[50] = "None";
MixSource[50] = "Warlock + Dragonslayer";
Class[50] = "Axe";
HP[50] = "120";
ATK[50] = "85";
DEF[50] = "51";
SPD[50] = "53";

Character[51] = "Ozymandias";
Spritename[51] = "Ozymandias";
Offensivesphere[51] = "Obliterate ATK I";
Defensivesphere[51] = "Regal Stance I";
Supportsphere[51] = "None";
MixSource[51] = "Dragoon + Dradonslayer";
Class[51] = "Lance";
HP[51] = "100";
ATK[51] = "100";
DEF[51] = "52";
SPD[51] = "54";

Character[52] = "Petra";
Spritename[52] = "Petra";
Offensivesphere[52] = "Barrage I";
Defensivesphere[52] = "None";
Supportsphere[52] = "None";
MixSource[52] = "Archer + Thief";
Class[52] = "Bow";
HP[52] = "92";
ATK[52] = "87";
DEF[52] = "54";
SPD[52] = "63";

Character[53] = "Promecia";
Spritename[53] = "Promecia";
Offensivesphere[53] = "None";
Defensivesphere[53] = "Aegis II";
Supportsphere[53] = "Guard I";
MixSource[53] = "Knight + Cleric";
Class[53] = "Crystal";
HP[53] = "110";
ATK[53] = "75";
DEF[53] = "65";
SPD[53] = "52";

Character[54] = "Prometheus";
Spritename[54] = "Prometheus";
Offensivesphere[54] = "Wide Slash I";
Defensivesphere[54] = "Aegis II";
Supportsphere[54] = "None";
MixSource[54] = "Dark Rune";
Class[54] = "/";
HP[54] = "78";
ATK[54] = "99";
DEF[54] = "45";
SPD[54] = "63";

Character[55] = "Ragnas";
Spritename[55] = "Ragnas";
Offensivesphere[55] = "Triple Punch II";
Defensivesphere[55] = "None";
Supportsphere[55] = "Boost SPD III";
MixSource[55] = "Monk + Berserker";
Class[55] = "Fist";
HP[55] = "85";
ATK[55] = "101";
DEF[55] = "51";
SPD[55] = "58";

Character[56] = "Randall";
Spritename[56] = "Randall";
Offensivesphere[56] = "Opus III";
Defensivesphere[56] = "Bolster SPD III";
Supportsphere[56] = "None";
MixSource[56] = "Alchemist + Druid";
Class[56] = "Tome";
HP[56] = "107";
ATK[56] = "87";
DEF[56] = "57";
SPD[56] = "49";

Character[57] = "Raven";
Spritename[57] = "Raven";
Offensivesphere[57] = "None";
Defensivesphere[57] = "None";
Supportsphere[57] = "None";
MixSource[57] = "Cleric + Druid";
Class[57] = "Staff";
HP[57] = "99";
ATK[57] = "84";
DEF[57] = "51";
SPD[57] = "70";

Character[58] = "Remmy";
Spritename[58] = "Remmy";
Offensivesphere[58] = "Quadra Punch I";
Defensivesphere[58] = "Deflect Projectiles II";
Supportsphere[58] = "None";
MixSource[58] = "Monk + Alchemist";
Class[58] = "Fist";
HP[58] = "110";
ATK[58] = "79";
DEF[58] = "55";
SPD[58] = "52";

Character[59] = "Rex";
Spritename[59] = "Rex";
Offensivesphere[59] = "Lightning Cut III";
Defensivesphere[59] = "None";
Supportsphere[59] = "None";
MixSource[59] = "Warrior + Mage";
Class[59] = "Sword";
HP[59] = "97";
ATK[59] = "91";
DEF[59] = "52";
SPD[59] = "60";

Character[60] = "Ringabolt";
Spritename[60] = "Ringabolt";
Offensivesphere[60] = "Obliterate DEF I";
Defensivesphere[60] = "Regal Stance I";
Supportsphere[60] = "None";
MixSource[60] = "Paladin + Dragonslayer";
Class[60] = "Axe";
HP[60] = "105";
ATK[60] = "94";
DEF[60] = "51";
SPD[60] = "54";

Character[61] = "Roland";
Spritename[61] = "Roland";
Offensivesphere[61] = "Quadra Slash I";
Defensivesphere[61] = "None";
Supportsphere[61] = "Interrupt Slash I";
MixSource[61] = "Rogue + Knight";
Class[61] = "Sword";
HP[61] = "102";
ATK[61] = "84";
DEF[61] = "56";
SPD[61] = "53";

Character[62] = "Rorick";
Spritename[62] = "Rorick";
Offensivesphere[62] = "Quadra Shot I";
Defensivesphere[62] = "Mimic III";
Supportsphere[62] = "None";
MixSource[62] = "Archer + Warlock";
Class[62] = "Gun";
HP[62] = "108";
ATK[62] = "93";
DEF[62] = "50";
SPD[62] = "54";

Character[63] = "Runeia";
Spritename[63] = "Runeia";
Offensivesphere[63] = "Quadcast I";
Defensivesphere[63] = "Countercast II";
Supportsphere[63] = "None";
MixSource[63] = "Warlock + Berserker";
Class[63] = "Staff";
HP[63] = "106";
ATK[63] = "86";
DEF[63] = "56";
SPD[63] = "56";

Character[64] = "Ruthie";
Spritename[64] = "Ruthie";
Offensivesphere[64] = "Obliterate Def I";
Defensivesphere[64] = "None";
Supportsphere[64] = "Boost ATK III";
MixSource[64] = "Rogue + Pirate";
Class[64] = "Gun";
HP[64] = "100";
ATK[64] = "92";
DEF[64] = "49";
SPD[64] = "55";

Character[65] = "Sasuke";
Spritename[65] = "Sasuke";
Offensivesphere[65] = "Focus III";
Defensivesphere[65] = "Ninjutsu I";
Supportsphere[65] = "None";
MixSource[65] = "Ninja + Warlock";
Class[65] = "Dagger";
HP[65] = "100";
ATK[65] = "93";
DEF[65] = "45";
SPD[65] = "63";

Character[66] = "Sidara";
Spritename[66] = "Sidara";
Offensivesphere[66] = "Awaken ATK III";
Defensivesphere[66] = "Bolster ATK III";
Supportsphere[66] = "None";
MixSource[66] = "Hunter + Berserker";
Class[66] = "Axe";
HP[66] = "102";
ATK[66] = "95";
DEF[66] = "54";
SPD[66] = "51";

Character[67] = "Tomnomo";
Spritename[67] = "Tomnomo";
Offensivesphere[67] = "Barrage I";
Defensivesphere[67] = "Brave Song III";
Supportsphere[67] = "None";
MixSource[67] = "Dark Rune";
Class[67] = "/";
HP[67] = "102";
ATK[67] = "87";
DEF[67] = "50";
SPD[67] = "57";

Character[68] = "Towell mage Juliet";
Spritename[68] = "Towel_mage_Juliet";
Offensivesphere[68] = "Quickcast I";
Defensivesphere[68] = "None";
Supportsphere[68] = "Interruptcast I";
MixSource[68] = "Summer band";
Class[68] = "";
HP[68] = "0";
ATK[68] = "0";
DEF[68] = "0";
SPD[68] = "0";

Character[69] = "Trill";
Spritename[69] = "Trill";
Offensivesphere[69] = "Grand Opus I";
Defensivesphere[69] = "Brave Song III";
Supportsphere[69] = "Symphony No.99 I";
MixSource[69] = "Goody bag";
Class[69] = "Harp";
HP[69] = "164";
ATK[69] = "74";
DEF[69] = "55";
SPD[69] = "56";

Character[70] = "Varus";
Spritename[70] = "Varus";
Offensivesphere[70] = "None";
Defensivesphere[70] = "Bolster DEF III";
Supportsphere[70] = "Guard I";
MixSource[70] = "Thief + Knight";
Class[70] = "Sword";
HP[70] = "110";
ATK[70] = "82";
DEF[70] = "60";
SPD[70] = "50";

Character[71] = "Vicious";
Spritename[71] = "Vicious";
Offensivesphere[71] = "Blunderblast I";
Defensivesphere[71] = "Quick Shot I";
Supportsphere[71] = "None";
MixSource[71] = "Berserker + Pirate";
Class[71] = "Gun";
HP[71] = "95";
ATK[71] = "95";
DEF[71] = "49";
SPD[71] = "58";

Character[72] = "Wallace";
Spritename[72] = "Wallace";
Offensivesphere[72] = "Grandshard I";
Defensivesphere[72] = "Bolster DEF III";
Supportsphere[72] = "None";
MixSource[72] = "Cleric + Paladin";
Class[72] = "Crystal";
HP[72] = "110";
ATK[72] = "89";
DEF[72] = "52";
SPD[72] = "49";

Character[73] = "Wedge";
Spritename[73] = "Wedge";
Offensivesphere[73] = "None";
Defensivesphere[73] = "Mimic III";
Supportsphere[73] = "Boost SPD III";
MixSource[73] = "Alchemist + Paladin";
Class[73] = "Potion";
HP[73] = "104";
ATK[73] = "85";
DEF[73] = "56";
SPD[73] = "57";

Character[74] = "Xerxes";
Spritename[74] = "Xerxes";
Offensivesphere[74] = "Grandbolt";
Defensivesphere[74] = "Deathtouch I";
Supportsphere[74] = "None";
MixSource[74] = "None";
Class[74] = "";
HP[74] = "105";
ATK[74] = "94";
DEF[74] = "51";
SPD[74] = "54";

Character[75] = "Yojimbo";
Spritename[75] = "Yojimbo";
Offensivesphere[75] = "Death Blossom III";
Defensivesphere[75] = "Deathtouch I";
Supportsphere[75] = "None";
MixSource[75] = "Ninja + Dragonslayer";
Class[75] = "Dagger";
HP[75] = "105";
ATK[75] = "80";
DEF[75] = "60";
SPD[75] = "62";

Character[76] = "Zaan";
Spritename[76] = "Zaan";
Offensivesphere[76] = "Awaken ATK III";
Defensivesphere[76] = "Bolster ATK III";
Supportsphere[76] = "None";
MixSource[76] = "Warrior + Pirate";
Class[76] = "Gun";
HP[76] = "97";
ATK[76] = "93";
DEF[76] = "52";
SPD[76] = "54";

Character[77] = "Zanmato";
Spritename[77] = "Zanmato";
Offensivesphere[77] = "Break DEF II";
Defensivesphere[77] = "Boost DEF III";
Supportsphere[77] = "None";
MixSource[77] = "Ninja + Dragoon";
Class[77] = "Lance";
HP[77] = "110";
ATK[77] = "89";
DEF[77] = "52";
SPD[77] = "59";

Character[78] = "Zeig";
Spritename[78] = "Zeig";
Offensivesphere[78] = "Brave Lightning III";
Defensivesphere[78] = "None";
Supportsphere[78] = "None";
MixSource[78] = "Necromancer + Dragonslayer";
Class[78] = "Tome";
HP[78] = "95";
ATK[78] = "102";
DEF[78] = "55";
SPD[78] = "52";


